# Generated by Django 4.1.6 on 2023-04-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='coords',
            field=models.CharField(default='Latitude: 17.3934 Longitude: 78.4706', max_length=10000),
            preserve_default=False,
        ),
    ]
