# Generated by Django 4.1.6 on 2023-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_bloodrequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='coords',
            field=models.CharField(default='Latitude: 17.3934 Longitude: 78.4706', max_length=400),
            preserve_default=False,
        ),
    ]
